### ISSUE TITLE
The KeyError when invalid value is passed to TimeflakeBinary

### ISSUE THREAD

**Issue by Salmela** [anthonynsimon/timeflake#17]
The `invalid` key does not exist anymore. I got this error
```
  File "/.../lib/python3.9/site-packages/timeflake/extensions/django/__init__.py", line 64, in to_python
    self.error_messages["invalid"], code="invalid", params={"value": value},
KeyError: 'invalid'
```

https://github.com/anthonynsimon/timeflake/blob/403900e278dde35af817046c7ae3513f5b951143/timeflake/extensions/django/__init__.py#L64

**Comment by anthonynsimon** [comment]
#18 fixed this, thank you!
