### ISSUE TITLE
UUID sortable?

### ISSUE THREAD

**Issue by derkan** [anthonynsimon/timeflake#2]
Is generated UUID sortable also?

**Comment by rany2** [comment]
Only `int`, `ts`, and `hex`

**Comment by anthonynsimon** [comment]
Yes you could sort on any of the representations and have them be equivalent:

```python
import timeflake

ids = [timeflake.random() for x in range(int(1e100))]

a = sorted(ids, key=lambda x: x.uuid)
b = sorted(ids, key=lambda x: x.int)
c = sorted(ids, key=lambda x: x.base62)

a == b == c
>> True
```

However, consider that it's roughly-ordered over time (millisecond granularity + 80 bits of entropy).

That means, you shouldn't use them for something that for example would require guaranteed ordering within a millisecond.

They can be pretty useful as a drop-in replacement for UUIDs for things like timeseries data, or user generated content that happens over time (like blog posts, comments, tweets). In the rare event of a collision, you could simply retry the transaction with a new one.

It's a tradeoff of performance and ordering vs guaranteed uniqueness.

Please do not use them as security keys, or other sensitive data which requires a higher level of entropy.
