### ISSUE TITLE
Object of type Timeflake is not JSON serializable

### ISSUE THREAD

**Issue by sebst** [anthonynsimon/timeflake#8]
When using `TimeflakePrimaryKeyBinary` in a Django model, it is not compatible with [DRF](https://www.django-rest-framework.org/) out of the box because of the above error message.

**Comment by anthonynsimon** [comment]
Thanks for the PR on this issue! From a first glance it looks good 💯, I will test it out in the coming days.

**Comment by sebst** [comment]
Thanks for your reply!

In addition to PR #9, I'd suggest to also subclass the `TimeflakeBinary` class from `UUIDField` which should solve additional issues with DRF. I'll try to submit another PR in the next days.
